### ISSUE TITLE
sign the go binaries using ldid and the ent.xml file, but they are still getting killed

### ISSUE THREAD

**Issue by mdipaw** [roothide/Bootstrap-basebin#1]
i'm sorry if this question is out of topic but i don't know where to ask to

**Comment by roothider** [comment]
on Bootstrap you also need to use `/basebin/fastPathSign $(jbroot)/path/to/file` to apply the CTBUG signature to binaries. (dpkg will auto apply it when installing deb files)

**Comment by mdipaw** [comment]
ok i'll compile the fakePathSign. thank you
